ignorePaths:
- .git
- .idea

skaConfig:
  ignorePaths:
  - "idea/*"
  - test-file-to-be-ignored-{{.testFileName}}.txt
  - "*.ignored"

inputs:
- placeholder: appName
  label: Application Name
  regexp: "^[a-zA-Z0-9_-]*$"
  help: The name of the application
  default: "test-app"

- placeholder: testFileName
  label: Test File Name
  help: The name of the test file
  default: "example"

- placeholder: listOfItems
  label: List of Items
  default: "one,two,three"

- placeholder: newVersion
  label: New Version
  minLength: 5
  help: The new version of the application
